### ISSUE TITLE
panic: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by doapp-jeremy** [Droplr/aws-env#25]
I am getting the following error when my container executes:
```
2018-12-05 00:26:51panic: MissingRegion: could not find region configuration
2018-12-05 00:26:51goroutine 1 [running]:
2018-12-05 00:26:51log.Panic(0xc420107ee0, 0x1, 0x1)
2018-12-05 00:26:51 /usr/local/Cellar/go/1.10.3/libexec/src/log/log.go:326 +0xc0
2018-12-05 00:26:51main.ExportVariables(0xc42000c0a0, 0xc42001600d, 0x21, 0x0, 0x75f5f8, 0x7, 0x0, 0x0)
2018-12-05 00:26:51 /Users/aorfin/go/aws-env/aws-env.go:62 +0x17d
2018-12-05 00:26:51main.main()
2018-12-05 00:26:51 /Users/aorfin/go/aws-env/aws-env.go:37 +0x193
2018-12-05 00:26:512018/12/05 06:26:51 MissingRegion: could not find region configuration
```
This seems to be some sort of AWS configuration issue, but my IAM role has permissions to for `ssm:Get*` on all resources.

Here is my Dockerfile:
```
FROM php:7.2.11-fpm

RUN apt-get update

RUN apt-get install wget

# Install opcache
RUN docker-php-ext-install opcache

# Install APCu
RUN pecl install apcu
RUN docker-php-ext-enable apcu

ADD webroot /webroot
ADD etc/zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf

RUN wget https://github.com/Droplr/aws-env/raw/9605a216913c18cf64338509204ca21379832b90/bin/aws-env-linux-amd64 -O /bin/aws-env && \
  chmod +x /bin/aws-env

CMD ["/bin/bash", "-c", "eval $(aws-env) && php-fpm"]
```
It is my understanding, and my debug shows, that the AWS_REGION env variable is set in my codebuild project that builds the image. I did try changing the last line to the following with the same result:
```
CMD ["/bin/bash", "-c", "eval $(AWS_REGION=$AWS_REGION aws-env) && php-fpm"]
```

**Comment by doapp-jeremy** [comment]
I figured out my problem.  I need to run the container with the AWS_REGION environment variable set, which is set via the aws task.
